name: AdminTools
version: 1.0.0
author: NeeZun
main: me.ollethunberg.admintools.Main
description: admin commands
commands:
    tools:
        description: /tl
        usage: /tools
        aliases: [tl]
    adminbook:
        description: /desk
        usage: /adminbook
        aliases: [ab]
